# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Liu Honghui
subtitle: Astrophysics
email: hhliu19@fudan.edu.cn
description: PhD student from Fudan University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://honghui-liu.github.io/pantheme" # the base hostname & protocol for your site, e.g. http://example.com
#url: "Users/honghui/Documents/website/panthera-jekyll-master/"
twitter_username: example
github_username:  honghui-liu

# Build settings
#markdown: kramdown

plugins:
  - jekyll-feed
  - html-proofer
  - bundler
  - rake
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

menu:
  - text: Home
    link: /
    icon: ""

  - text: Resume
    link: /resume
    icon: ""

  - text: Skills 
    link: /skills-and-offers
    icon: ""

  - text: Blogs
    link: /blog
    icon: ""


social_icons:
  - name: github
    link: https://github.com/honghui-liu
    icon: fab fa-github-square
  
  - name: email
    link: hhliu19@fudan.edu.cn
    icon: fas fa-envelope-open-text
  
  
